CREATE DATABASE TO_WATCH;
USE to_watch;
# Genre table
CREATE TABLE GENRE (
	GEN_ID INTEGER AUTO_INCREMENT NOT NULL,
    GEN_NAME VARCHAR(50) NOT NULL,
    CONSTRAINT GEN_PK PRIMARY KEY (GEN_ID)
);

# Category table
CREATE TABLE CATEGORY (
	CAT_ID INTEGER AUTO_INCREMENT NOT NULL,
    CAT_NAME VARCHAR (50),
    CONSTRAINT CAT_PK PRIMARY KEY (CAT_ID)
);

# Classification tableu
CREATE TABLE CLASSIFICATION (
	CLF_ID INTEGER AUTO_INCREMENT NOT NULL,
    CLF_NAME VARCHAR (50) NOT NULL,
    CONSTRAINT CLF_PK PRIMARY KEY (CLF_ID)
);

# Director table
CREATE TABLE DIRECTOR (
	DIR_ID INTEGER AUTO_INCREMENT NOT NULL,
    DIR_NAME VARCHAR (50) NOT NULL,
    DIR_COUNTRY VARCHAR (50) NOT NULL,
    CONSTRAINT DIR_PK PRIMARY KEY (DIR_ID)
);

# User table
CREATE TABLE USER (
	USR_ID INTEGER AUTO_INCREMENT NOT NULL,
    USR_NAME VARCHAR (50) NOT NULL,
    USR_NICKNAME VARCHAR (30) NOT NULL,
    USR_EMAIL VARCHAR (50) NOT NULL,
    USR_PASSWORD VARCHAR (10) NOT NULL,
    USR_DT_CAD TIMESTAMP NOT NULL,
    CONSTRAINT USR_PK PRIMARY KEY (USR_ID)
);

#Content table
CREATE TABLE CONTENT (
	CONT_ID INTEGER AUTO_INCREMENT NOT NULL,
    CONT_NAME VARCHAR (50) NOT NULL,
    CONT_OVERVIEW VARCHAR (200) NOT NULL,
    CONT_COUNTRY VARCHAR (20) NOT NULL,
    CONT_DURATION VARCHAR (5) NOT NULL,
    CONT_POSTER VARCHAR (50) NOT NULL,
    CONT_TRAILER VARCHAR (50) NOT NULL,
    CONT_RATING VARCHAR (5) NOT NULL,
    CONT_CLF_ID INTEGER NOT NULL,
    CONT_CAT_ID INTEGER NOT NULL,
	CONT_WATCHED BOOLEAN NOT NULL,
    CONSTRAINT CONT_PK PRIMARY KEY (CONT_ID),
    CONSTRAINT CONT_CAT_FK FOREIGN KEY (CONT_CAT_ID) REFERENCES CATEGORY (CAT_ID),
    CONSTRAINT CONT_CLF_FK FOREIGN KEY (CONT_CLF_ID) REFERENCES CLASSIFICATION (CLF_ID)
);

# Table User List
CREATE TABLE USER_LIST (
	USRL_USR_ID INTEGER NOT NULL,
    USRL_CONT_ID INTEGER NOT NULL,
    CONSTRAINT USRL_USR_FK FOREIGN KEY (USRL_USR_ID) REFERENCES USER (USR_ID),
    CONSTRAINT USRL_CONT_ID FOREIGN KEY (USRL_CONT_ID) REFERENCES CONTENT (CONT_ID)
);

# Tabela Genero Conteudo
CREATE TABLE GENRE_CONTENT (
	GCONT_GEN_ID INTEGER NOT NULL,
    GCONT_CONT_ID INTEGER NOT NULL,
    CONSTRAINT GCONT_GEN_FK FOREIGN KEY (GCONT_GEN_ID) REFERENCES GENRE (GEN_ID),
    CONSTRAINT GCONT_CONT_FK FOREIGN KEY (GCONT_CONT_ID) REFERENCES CONTENT (CONT_ID)
);

# Tabela Diretor Conteudo
CREATE TABLE CONTENT_DIRECTOR (
	CTD_DIR_ID INTEGER NOT NULL,
    CTD_CONT_ID INTEGER NOT NULL,
    CONSTRAINT CTD_DIR_FK FOREIGN KEY (CTD_DIR_ID) REFERENCES DIRECTOR (DIR_ID),
    CONSTRAINT CTD_CONT_FK FOREIGN KEY (CTD_CONT_ID) REFERENCES CONTENT (CONT_ID)
);

# Popula tbl_CLASSIFICACAO
INSERT INTO classification (clf_name) VALUES ("Livre para todos os Públicos");
INSERT INTO classification (clf_name) VALUES ("Não recomendado para menores de 10 anos");
INSERT INTO classification (clf_name) VALUES ("Não recomendado para menores de 12 anos");
INSERT INTO classification (clf_name) VALUES ("Não recomendado para menores de 14 anos");
INSERT INTO classification (clf_name) VALUES ("Não recomendado para menores de 16 anos");
INSERT INTO classification (clf_name) VALUES ("Não recomendado para menores de 18 anos");

# Popula tbl_genero
INSERT INTO genre (gen_name) VALUES ("Ação");
INSERT INTO genre (gen_name) VALUES ("Animação");
INSERT INTO genre (gen_name) VALUES ("Aventura");
INSERT INTO genre (gen_name) VALUES ("Comédia");
INSERT INTO genre (gen_name) VALUES ("Drama");
INSERT INTO genre (gen_name) VALUES ("Fantasia");
INSERT INTO genre (gen_name) VALUES ("Ficção Científica");
INSERT INTO genre (gen_name) VALUES ("Guerra");
INSERT INTO genre (gen_name) VALUES ("Luta");
INSERT INTO genre (gen_name) VALUES ("Musicais");
INSERT INTO genre (gen_name) VALUES ("Romance");
INSERT INTO genre (gen_name) VALUES ("Policial");
INSERT INTO genre (gen_name) VALUES ("Terror");

# Popula tbl_category
INSERT INTO category (cat_name) VALUES ("Animes");
INSERT INTO category (cat_name) VALUES ("Filmes");
INSERT INTO category (cat_name) VALUES ("Séries");